Appchoco/urls.py
from django.urls import path
from Appchoco.views import *
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('In/',inicio,name="Inicio"),    
    path('contacto/',contacto,name="Contacto"),
    path('about/',about,name="About"),

    #########Productos #####
    path('leerproduc/',leeproductos,name = "productos"),
    path('bchoco/',busqueda_chocolate,name ="buscarc"),    
    path('buscar/',buscar), 
    path('chocolates/',chocolateForm,name="Agregar_Choco"),
    path('editarChoco/<nombres>',editarchoco,name="Editar_choco"),
    path('borrarChoco/<nombre1>',productosEli,name="Borrar_choco"),

    ###### Usuario ###
    path('registro/',registrar,name="registro"),
    path('login/',iniciar_sesion1,name="Login"),###Usurio###    
    path('cerrar',LogoutView.as_view(template_name="Appchoco/cerrar.html"),name="Cerrar"),
    path('editarUsuario/',editarU,name="EditarUsu"),
    path('agregar_editarImg/',agregar_editar_avatar,name="Agregar_editar_avatar"),
    path('borrarAvatar/<user>',borraAvatar,name="Borrar_avatar"),        
    path('modificar/',modificar,name='Modificar'),

 
    

    ###  Usando Class ####    

    path('mensajeC/', MensajeLis.as_view(),name = "LeerMensajes"), ### Leer ###
    path('mensajeC/nuevo', MensajeCrear.as_view(),name ="CrearMensaje"),   ### Crear ### 
    path("mensajeC/<int:pk>",MensajeDetalle.as_view(),name="DetalleMensaje"),### Detalle ###
    path('mensajeC/editar/<int:pk>',MensajeUptade.as_view(),name="EditarMensaje"),### Editar ###
    path('mensajeC/borrar/<int:pk>',Mensajeborrar.as_view(),name="BorrarMensaje"),### Borrar ###
    

 
]

Appchoco/models.py
from distutils.command.upload import upload
import email
from django.db import models
from django.contrib.auth.models import User


class Productos(models.Model):
    def __str__(self):
        return f"Usuaria {self.nombre}"
    
    nombre= models.CharField(max_length=60)
    precio = models.IntegerField()   
    sabor = models.CharField(max_length=60)
    imagen = models.ImageField(upload_to='images',null=True,blank=True)



class Contactos(models.Model):
    def __str__(self):
        return f"Contacto {self.nombre} {self.email}"
    nombre = models.CharField(max_length=60)    
    email = models.EmailField()
    mensaje = models.TextField()

class Avatar(models.Model):
    user= models.ForeignKey(User,on_delete=models.CASCADE)
    imagen=models.ImageField(upload_to="avatares",null=True,blank=True)

Appchoco/templates/Appchoco/agreImagen.html
{% extends "Appchoco/padre.html"%}
{%load static %}
{% block titulo %}
<h1>Agregar imagen</h1>

{% endblock titulo %}
{% block parrafo %}
<H1>Agregar imagen</h1>
<form action="" method="POST" enctype="multipart/form-data"> {%csrf_token%}
    <p>{{Miform.as_p}} </p>     
    <input type="submit" class="btn btn-info" value ='Subir imagen '>
    <a class="btn btn-info" href="{% url 'Borrar_avatar' user %}">Borrar avatar</a>
</form>   
     
{% endblock parrafo %}

Appchoco/templates/Appchoco/borrarChoco.html
{% extends "Appchoco/padre.html"%}

{%load static %}
{% block titulo %}
Productos

{% endblock titulo %}
{% block parrafo %}
<h1 style="color:darkcyan">Borrar Chocolate </h1> 

 <table>
    {{choco2.as_p}}
    


 </table>

 <input type="submit" value="Enviar" >

 {% endblock parrafo %}

Appchoco/templates/Appchoco/choco.html
{% extends "Appchoco/padre.html"%}

{%load static %}
{% block titulo %}
Productos

{% endblock titulo %}
{% block parrafo %}
<h1 style="color:darkcyan">Agregar Chocolate </h1> 
 <form action=""method="POST"  enctype="multipart/form-data">{% csrf_token %}

    
 <table>
    {{ choco1.as_table }}
    


 </table>

 <input type="submit" value="Enviar" >

 {% endblock parrafo %}

Appchoco/templates/Appchoco/contactos_confirm_delete.html
{% extends "Appchoco/padre.html"%}
{%load static %}
{% block titulo %}
Eliminar Mensaje

{% endblock titulo %}
{% block parrafo %}
<form action="" method="POST">{% csrf_token %}
    <p>Deseas eliminar: {{contactos.nombre}}?</p>
    <input type="submit" value="Confirmar">




</form>
{% endblock parrafo %}              

Appchoco/templates/Appchoco/contactos_detail.html
{% extends "Appchoco/padre.html"%}
{%load static %}
{% block titulo %}
Detalles de mesaje

{% endblock titulo %}
{% block parrafo %}
<p>Mensaje de : {{contactos.nombre}}</p>
<p>Detalle de Email: {{contactos.email}}</p>
<p>Detalle de mensaje: {{contactos.mensaje}}</p>

<a class="btn btn-outline-info" href="{% url 'LeerMensajes' %}">Regresar</a>  






{% endblock parrafo %}

Appchoco/templates/Appchoco/contactos_form.html
{% extends "Appchoco/padre.html"%}
{%load static %}
{% block titulo %}
Escribe un  Mensaje

{% endblock titulo %}
{% block parrafo %}
<h1 style="color :rgb(24, 24, 204)">Mensaje</h1>
<form action=""method="POST">{% csrf_token %}
    <table>
        {{form.as_table}}</a>
        </table>   
   
        <input type="submit" style="color :rgb(13, 13, 224)" value ='Enviar'>

    


</form>
{% endblock parrafo %}

Appchoco/templates/Appchoco/contactos_list.html
{% extends "Appchoco/padre.html"%}
{%load static %}
{% block titulo %}
Aca esta todos los mensajes

{% endblock titulo %}
{%block parrafo%}
<h1 style="color:royalblue"> Todo los mensajes</h1>{% csrf_token %}
     {%for men in object_list%}
    <ul>
        <li>Nombre: {{men.nombre}}</li>
        <li>Mensaje : {{men.mensaje}}</li>
        <a style="color:rgb(37, 73, 150) " href="{% url 'DetalleMensaje' men.id%}">Ver detalle</a>
        <a style="color:rgb(37, 73, 150) " href="{% url 'EditarMensaje' men.id %}">Editar</a>
        <a style="color:rgb(37, 73, 150) " href="{% url 'BorrarMensaje' men.id%}">Borrar</a>
    </ul>
      
    {%endfor%}
    <a href="{% url 'CrearMensaje' %}">Crear mensaje</a>  

    {%endblock parrafo%}

Appchoco/templates/Appchoco/editarU.html
{% extends "Appchoco/padre.html"%}

{%load static %}
{% block titulo %}
Editar...!!!

{% endblock titulo %}
{% block parrafo %}
<h1 style="color:darkcyan">Editar Usuario :{{usuario}}</h1> 
 <form action=""method="POST">{% csrf_token %}    
     <table>
        {{miformu.as_table}}
    </table>
 <input type="submit" value="Enviar" >
 

 </form>

{% endblock parrafo %}

Appchoco/templates/Appchoco/editarchoco.html
{% extends "Appchoco/padre.html"%}

{%load static %}
{% block titulo %}
Queremos saber un poco de vos!!
Gracias por venir!!!

{% endblock titulo %}
{% block parrafo %}
<h1 style="color:darkcyan">Editar choco </h1> 
<form action=""method="POST" enctype="multipart/form-data">{% csrf_token %}
<table>
{{choco2.as_p}}
</table>
<input type="submit" value="Enviar" >
</form>

{% endblock parrafo %}

Appchoco/templates/Appchoco/login.html
{% extends "Appchoco/padre.html"%}
{%load static %}
{% block titulo %}
Iniciar Sesion
{% endblock titulo %}
{% block parrafo %}
<form action=""method="POST">{% csrf_token %}
  {{formPas.as_p}}
  <button type="submit" style="color:blue">Iniciar Sesion</button>
</form>
{% endblock parrafo %}

Appchoco/templates/Appchoco/modificaciones.html
{% extends "Appchoco/padre.html"%}

{%load static %}
{% block titulo %}
Editar usuario...!!!

{% endblock titulo %}
{% block parrafo %}
<a class="btn btn-info" href="{% url 'Agregar_editar_avatar' %}">Editar Avatar</a>           
<a class="btn btn-info" href="{% url 'EditarUsu' %}">Editar Usuario</a>



{% endblock parrafo %}

Appchoco/templates/Appchoco/padre.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Landing Page - Start Bootstrap Theme</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'Appchoco/assets/favicon.ico'%}" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'Appchoco/css/styles.css'%}" rel="stylesheet" />
        <style type="text/css">
            .avatar{
                border-radius: 50%;
                height:40px;
                width:40px;
                overflow:hidden;
                position:relative;
            }                   
            .avatar img {
                display: block;
                height: 100%;
                position: absolute;
                left: 50%;
                transform: translateX(-50%);                      
            }
          </style>

    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-dark" style="background-color: #2e1616;">
            <div class="container">
               
                
                <a class="navbar-brand" href="{% url 'Inicio' %}">Inicio</a>
                <a class="navbar-brand" href="{% url 'Contacto' %}">Contacto</a>  
                <a class="navbar-brand" href="{% url 'About' %}">About</a> 
                
                
                {%if request.user.is_authenticated%}
                
                
                <a class="navbar-brand" href="{% url 'productos' %}">Productos</a>                       
                <a class="bi bi-search navbar-brand" href="{% url 'buscarc' %}">Buscar</a>    

                <p class="bi bi-person-circle"  style="color  : rgb(107, 107, 175)">{{user}}</p>
                            
                {%with first_image=user.avatar_set.first %}
                    {%if first_image %}
                        <img  src="{{first_image.imagen.url}}" class="avatar" alt="">
                    {%endif%}

                {%endwith%} 
                
                <a class="bi bi-door-closed-fill btn btn-info" href="{% url 'Modificar' %}">Editar perfil</a>                                           
                <a class="bi bi-door-closed-fill btn btn-info" href="{% url 'Cerrar' %}">Salir</a>
                
                {%else%}
                
                <a class="bi bi-door-open-fill btn btn-info" href="{% url 'Login' %}">Iniciar Sesion</a>
                <a class="bi bi-person-fill btn btn-info" href="{%url 'registro'%}">Registrar</a>
                
                
                {%endif%}
                
                
            </div>
        </nav>
        <!-- Masthead-->
        
        <header class=" bg-image-full" style="width:100%;height:400px;background-image: url('https://www.wallpaperuse.com/wallp/33-337297_m.jpg')">
            +<div class="container position-relative">                
                +<div class="row justify-content-center">
                    <div class="col-xl-5">
                        +<div class="text-center" style="color: rgb(247, 247, 247);" >
                            <!-- Page heading-->
                            <h1 class="mb-6">
                                
                                {% block titulo %}
                                
                                {% endblock titulo %}
                            
                            </h1>
                            <!-- Signup form-->
                            <!-- * * * * * * * * * * * * * * *-->
                            <!-- * * SB Forms Contact Form * *-->
                            <!-- * * * * * * * * * * * * * * *-->
                            <!-- This form is pre-integrated with SB Forms.-->
                            <!-- To make this form functional, sign up at-->
                            <!-- https://startbootstrap.com/solution/contact-forms-->
                            <!-- to get an API token!-->
                            
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- Aca hice un parrafo-->
        {% block parrafo %}
                             
        {% endblock parrafo %}
        <!-- Footer-->
        <footer class="footer bg-light">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 h-100 text-center text-lg-start my-auto">
                        <ul class="list-inline mb-2">
                           
                        </ul>
                        <p class="text-muted small mb-4 mb-lg-0">&copy; Your Website 2022. All Rights Reserved.</p>
                    </div>
                    <div class="col-lg-6 h-100 text-center text-lg-end my-auto">
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi bi-suit-heart-fill fs-3"></i></a>
                            </li>
                            <li class="list-inline-item me-4">
                                <a href="{% url 'LeerMensajes'%}"><i class="bi bi-envelope fs-3"></i></a>

                        </ul>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

Appchoco/templates/Appchoco/productos.html
{% extends "Appchoco/padre.html"%}
{%load static %}
{% block titulo %}
Productos!!!!
{% endblock titulo %}
{% block parrafo %}
    <h2 style="color:darkcyan">Lista de productos!!!</h2> 
    
    
       
    {% for x in miproductos %}
        <p>Chocolate : {{x.nombre}}</p>
        <p>Sabor : {{x.sabor}}</p>   
        <p>Precio : {{x.precio}}</p>   
        <img style=width:10% src="{{x.imagen.url}}" alt="">
        <div>    
        <button>
            <a href="{% url 'Editar_choco' x.nombre %}">Editar</a> 
        </button>
      
        <button>
            <a href="{% url 'Borrar_choco' x.nombre %}">Delete</a>
        </button>
        
        </div>    
    {% endfor %}
  
 <div><a class="btn btn-info" href="{% url 'Agregar_Choco' %}">Agregar</a></div>      



   

{% endblock parrafo %}

Appchoco/templates/Appchoco/registro.html
{% extends "Appchoco/padre.html"%}
{%load static %}
{% block titulo %}
<h1>Registrate </h1>

{% endblock titulo %}
{% block parrafo %}
<form action=""method="POST">{% csrf_token %}
   <h2 style="color: rgb(36, 36, 177)">Ingrese sus datos</h2>
   <table>{{formularioUsuario.as_p}}</table>
   <button type="submit" class="btn btn-outline-info" style="color:rgb(41, 41, 175)">Registrar</button>
 </form>
{% endblock parrafo %}